CREATE TYPE "GigStatus_new" AS ENUM (
  'POSTED',
  'SEARCHING_FOR_WORKER',
  'WORKER_ASSIGNED',
  'WORKER_EN_ROUTE',
  'WORKER_ARRIVED',
  'IN_PROGRESS',
  'COMPLETED',
  'CANCELLED',
  'DRAFT',
  'DISPUTED'
);

ALTER TABLE "Gig" ALTER COLUMN "status" DROP DEFAULT;

ALTER TABLE "Gig" ALTER COLUMN "status" TYPE "GigStatus_new" USING (
  CASE "status"::text
    WHEN 'OPEN' THEN 'SEARCHING_FOR_WORKER'
    WHEN 'MATCHED' THEN 'WORKER_ASSIGNED'
    WHEN 'EN_ROUTE' THEN 'WORKER_EN_ROUTE'
    ELSE "status"::text
  END::"GigStatus_new"
);

DROP TYPE "GigStatus";
ALTER TYPE "GigStatus_new" RENAME TO "GigStatus";
ALTER TABLE "Gig" ALTER COLUMN "status" SET DEFAULT 'SEARCHING_FOR_WORKER';
