-- Payment flow v2: free posting, worker selection, timer fields

CREATE TYPE "PricingType" AS ENUM ('FIXED', 'HOURLY', 'ESTIMATE_TIMER');
CREATE TYPE "GigInterestStatus" AS ENUM ('INTERESTED', 'SELECTED', 'REJECTED', 'WITHDRAWN');

ALTER TYPE "GigStatus" ADD VALUE IF NOT EXISTS 'WORKER_SELECTED';
ALTER TYPE "GigStatus" ADD VALUE IF NOT EXISTS 'WAITING_EXTRA_TIME_APPROVAL';
ALTER TYPE "GigStatus" ADD VALUE IF NOT EXISTS 'WAITING_CUSTOMER_CONFIRMATION';

ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "pricingType" "PricingType" NOT NULL DEFAULT 'HOURLY';
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "publishedAt" TIMESTAMP(3);
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "authorizedAt" TIMESTAMP(3);
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "customerApprovedAt" TIMESTAMP(3);
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "autoApproveAt" TIMESTAMP(3);
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "taxCents" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "finalTotalCents" INTEGER;

ALTER TABLE "Gig" ALTER COLUMN "status" SET DEFAULT 'POSTED';

UPDATE "Gig"
SET "publishedAt" = COALESCE("publishedAt", "createdAt")
WHERE "status" IN ('POSTED', 'SEARCHING_FOR_WORKER', 'WORKER_ASSIGNED', 'WORKER_EN_ROUTE', 'WORKER_ARRIVED', 'IN_PROGRESS', 'COMPLETED');

CREATE TABLE IF NOT EXISTS "GigInterest" (
    "id" TEXT NOT NULL,
    "gigId" TEXT NOT NULL,
    "workerId" TEXT NOT NULL,
    "status" "GigInterestStatus" NOT NULL DEFAULT 'INTERESTED',
    "offeredWorkerPayoutCents" INTEGER,
    "estimatedArrivalMinutes" INTEGER,
    "estimatedHours" DECIMAL(5,2),
    "message" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "GigInterest_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "GigInterest_gigId_workerId_key" ON "GigInterest"("gigId", "workerId");
CREATE INDEX IF NOT EXISTS "GigInterest_gigId_status_idx" ON "GigInterest"("gigId", "status");

ALTER TABLE "GigInterest" ADD CONSTRAINT "GigInterest_gigId_fkey" FOREIGN KEY ("gigId") REFERENCES "Gig"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "GigInterest" ADD CONSTRAINT "GigInterest_workerId_fkey" FOREIGN KEY ("workerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "GigAssignment" ADD COLUMN IF NOT EXISTS "enRouteAt" TIMESTAMP(3);
ALTER TABLE "GigAssignment" ADD COLUMN IF NOT EXISTS "arrivedAt" TIMESTAMP(3);
ALTER TABLE "GigAssignment" ADD COLUMN IF NOT EXISTS "endedAt" TIMESTAMP(3);
ALTER TABLE "GigAssignment" ADD COLUMN IF NOT EXISTS "startLatitude" DECIMAL(9,6);
ALTER TABLE "GigAssignment" ADD COLUMN IF NOT EXISTS "startLongitude" DECIMAL(9,6);
ALTER TABLE "GigAssignment" ADD COLUMN IF NOT EXISTS "endLatitude" DECIMAL(9,6);
ALTER TABLE "GigAssignment" ADD COLUMN IF NOT EXISTS "endLongitude" DECIMAL(9,6);
ALTER TABLE "GigAssignment" ADD COLUMN IF NOT EXISTS "billableMinutes" INTEGER;
ALTER TABLE "GigAssignment" ADD COLUMN IF NOT EXISTS "timerPausedAt" TIMESTAMP(3);
ALTER TABLE "GigAssignment" ADD COLUMN IF NOT EXISTS "extraTimeApprovedMinutes" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GigAssignment" ADD COLUMN IF NOT EXISTS "completionNotes" TEXT;
ALTER TABLE "GigAssignment" ADD COLUMN IF NOT EXISTS "completionPhotoUrls" TEXT[] DEFAULT ARRAY[]::TEXT[];
