/** Development flow event names for DUTS gig lifecycle logging. */
export const DUTS_FLOW_EVENTS = [
  "REQUEST_STARTED",
  "GIG_CREATED",
  "GIG_ID_RECEIVED",
  "NAVIGATION_STARTED",
  "MATCHING_STARTED",
  "OFFER_SENT",
  "WORKER_ACCEPTED",
  "MATCHING_STOPPED",
  "TAX_CALCULATED",
  "PAYMENT_AUTHORIZED",
  "GIG_STARTED",
  "GIG_COMPLETED",
  "PAYMENT_CAPTURED",
  "WORKER_EARNINGS_CREATED",
  "REVIEW_SKIPPED",
  "REVIEW_SUBMITTED",
  "HOME_REDIRECTED",
  /** DUTS Delivery (fulfillmentType=DELIVERY) */
  "DELIVERY_QUOTE",
  "DELIVERY_REQUESTED",
  "COURIER_INTEREST",
  "COURIER_ASSIGNED",
  "PACKAGE_COLLECTED",
  "DELIVERY_VERIFIED",
  "DELIVERY_CANCELLED",
  "PAYMENT_FAILED",
  /** Stage 4 commerce */
  "COMMERCE_ORDER_CONFIRMED",
  "COMMERCE_MERCHANT_ACCEPTED",
  "COMMERCE_READY_FOR_PICKUP",
  "COMMERCE_DELIVERED",
  "COMMERCE_READY_IDEMPOTENT",
  "COMMERCE_MERCHANT_TIMEOUT",
  "COMMERCE_BASKET_CREATED",
  "COMMERCE_QUOTE_GENERATED",
  "COMMERCE_MERCHANT_REJECTED",
  "COMMERCE_PRODUCT_UNAVAILABLE",
  "COMMERCE_PRICE_CHANGED",
  "COMMERCE_CART_MUTATED",
  "COMMERCE_CART_EXPIRED",
  "COMMERCE_BUDGET_EXCEEDED",
  "COMMERCE_QUOTE_INVALIDATED",
  "COMMERCE_MERCHANT_NOTIFIED",
  "WHATSAPP_INBOUND",
  "WHATSAPP_SEARCH"
] as const;

export type DutsFlowEvent = (typeof DUTS_FLOW_EVENTS)[number];

export type DutsFlowLogPayload = {
  event: DutsFlowEvent;
  gigId?: string;
  userId?: string;
  userRole?: string;
  platform?: "web" | "mobile" | "api";
  timestamp?: string;
  meta?: Record<string, string | number | boolean | null | undefined>;
};
