export const BRANDED_ACQUISITION_PLAN = [
  {
    "catalogProductId": "22cfda60-bc89-456d-9989-4654436d6b96",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "7up",
    "plannedBrand": "7up",
    "plannedSizeLabel": "2L",
    "plannedCategory": "Soft Drinks",
    "brandFamily": "7up",
    "acquisitionPack": "PACK_A_BEVERAGES",
    "acquisitionPriority": "BRANDED_PRIORITY_A",
    "regionalPackageRisk": "MEDIUM",
    "brandMetadataReview": false,
    "likelyBrand": "7up",
    "referenceImageUrl": null,
    "notes": "500ml vs 2L separately. Do not reuse existing 1L."
  },
  {
    "catalogProductId": "d8ac79e7-ba40-4f9f-b685-d2cf45ded3bb",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "7up",
    "plannedBrand": "7up",
    "plannedSizeLabel": "500ml",
    "plannedCategory": "Soft Drinks",
    "brandFamily": "7up",
    "acquisitionPack": "PACK_A_BEVERAGES",
    "acquisitionPriority": "BRANDED_PRIORITY_A",
    "regionalPackageRisk": "MEDIUM",
    "brandMetadataReview": false,
    "likelyBrand": "7up",
    "referenceImageUrl": null,
    "notes": "500ml vs 2L separately. Do not reuse existing 1L."
  },
  {
    "catalogProductId": "0124f94e-4f05-40d3-8c34-194bf3e15ede",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Coca-Cola",
    "plannedBrand": "Coca-Cola",
    "plannedSizeLabel": "1L",
    "plannedCategory": "Soft Drinks",
    "brandFamily": "Coca-Cola",
    "acquisitionPack": "PACK_A_BEVERAGES",
    "acquisitionPriority": "BRANDED_PRIORITY_A",
    "regionalPackageRisk": "HIGH",
    "brandMetadataReview": false,
    "likelyBrand": "Coca-Cola",
    "referenceImageUrl": null,
    "notes": "Do not use Coca-Cola Zero for regular Coca-Cola. Photograph 330ml, 500ml, 1L, and 2L separately."
  },
  {
    "catalogProductId": "4d9979f1-b0ef-4954-b0f3-a806165765e6",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Coca-Cola",
    "plannedBrand": "Coca-Cola",
    "plannedSizeLabel": "2L",
    "plannedCategory": "Soft Drinks",
    "brandFamily": "Coca-Cola",
    "acquisitionPack": "PACK_A_BEVERAGES",
    "acquisitionPriority": "BRANDED_PRIORITY_A",
    "regionalPackageRisk": "HIGH",
    "brandMetadataReview": false,
    "likelyBrand": "Coca-Cola",
    "referenceImageUrl": null,
    "notes": "Do not use Coca-Cola Zero for regular Coca-Cola. Photograph 330ml, 500ml, 1L, and 2L separately."
  },
  {
    "catalogProductId": "705942f1-b491-4943-9a79-97cd2c589ff0",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Coca-Cola",
    "plannedBrand": "Coca-Cola",
    "plannedSizeLabel": "330ml",
    "plannedCategory": "Soft Drinks",
    "brandFamily": "Coca-Cola",
    "acquisitionPack": "PACK_A_BEVERAGES",
    "acquisitionPriority": "BRANDED_PRIORITY_A",
    "regionalPackageRisk": "HIGH",
    "brandMetadataReview": false,
    "likelyBrand": "Coca-Cola",
    "referenceImageUrl": null,
    "notes": "Do not use Coca-Cola Zero for regular Coca-Cola. Photograph 330ml, 500ml, 1L, and 2L separately."
  },
  {
    "catalogProductId": "fc15354a-ec7f-4449-9e2b-b54ed032c4fb",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Coca-Cola",
    "plannedBrand": "Coca-Cola",
    "plannedSizeLabel": "500ml",
    "plannedCategory": "Soft Drinks",
    "brandFamily": "Coca-Cola",
    "acquisitionPack": "PACK_A_BEVERAGES",
    "acquisitionPriority": "BRANDED_PRIORITY_A",
    "regionalPackageRisk": "HIGH",
    "brandMetadataReview": false,
    "likelyBrand": "Coca-Cola",
    "referenceImageUrl": null,
    "notes": "Do not use Coca-Cola Zero for regular Coca-Cola. Photograph 330ml, 500ml, 1L, and 2L separately."
  },
  {
    "catalogProductId": "baf50e0f-2589-403a-957a-f78b95374878",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Coca-Cola Zero",
    "plannedBrand": "Coca-Cola",
    "plannedSizeLabel": "500ml",
    "plannedCategory": "Soft Drinks",
    "brandFamily": "Coca-Cola Zero",
    "acquisitionPack": "PACK_A_BEVERAGES",
    "acquisitionPriority": "BRANDED_PRIORITY_A",
    "regionalPackageRisk": "HIGH",
    "brandMetadataReview": false,
    "likelyBrand": "Coca-Cola",
    "referenceImageUrl": null,
    "notes": "Must be Zero, not regular Coca-Cola. Zimbabwe Zero branding, not US Coke Zero Sugar if they differ."
  },
  {
    "catalogProductId": "c6945c26-8bf2-42e6-9dde-7e8b7ea42779",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Fanta Orange",
    "plannedBrand": "Fanta",
    "plannedSizeLabel": "2L",
    "plannedCategory": "Soft Drinks",
    "brandFamily": "Fanta",
    "acquisitionPack": "PACK_A_BEVERAGES",
    "acquisitionPriority": "BRANDED_PRIORITY_A",
    "regionalPackageRisk": "HIGH",
    "brandMetadataReview": false,
    "likelyBrand": "Fanta",
    "referenceImageUrl": null,
    "notes": "Must be Fanta Orange, not grape/pineapple. 500ml and 2L separately."
  },
  {
    "catalogProductId": "a112ae11-bc0c-4c82-9a68-b0f14097b9f6",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Fanta Orange",
    "plannedBrand": "Fanta",
    "plannedSizeLabel": "500ml",
    "plannedCategory": "Soft Drinks",
    "brandFamily": "Fanta",
    "acquisitionPack": "PACK_A_BEVERAGES",
    "acquisitionPriority": "BRANDED_PRIORITY_A",
    "regionalPackageRisk": "HIGH",
    "brandMetadataReview": false,
    "likelyBrand": "Fanta",
    "referenceImageUrl": null,
    "notes": "Must be Fanta Orange, not grape/pineapple. 500ml and 2L separately."
  },
  {
    "catalogProductId": "ca052455-a6de-468f-a583-10581dc80f8a",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Mazoe Orange Crush",
    "plannedBrand": "Mazoe",
    "plannedSizeLabel": "1L",
    "plannedCategory": "Juices",
    "brandFamily": "Mazoe",
    "acquisitionPack": "PACK_A_BEVERAGES",
    "acquisitionPriority": "BRANDED_PRIORITY_A",
    "regionalPackageRisk": "LOW",
    "brandMetadataReview": false,
    "likelyBrand": "Mazoe",
    "referenceImageUrl": "https://api.duts.tech/v1/media/product-image/87a9e41a-efe7-4d5d-af0e-205d90f9d88e.jpg",
    "notes": "Orange Crush \u2260 Raspberry. 1L \u2260 5L. Do not reuse Mazoe Blackberry."
  },
  {
    "catalogProductId": "825bd247-9efa-47bd-90c0-7d9ca6c126d1",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Mazoe Raspberry",
    "plannedBrand": "Mazoe",
    "plannedSizeLabel": "2L",
    "plannedCategory": "Juices",
    "brandFamily": "Mazoe",
    "acquisitionPack": "PACK_A_BEVERAGES",
    "acquisitionPriority": "BRANDED_PRIORITY_A",
    "regionalPackageRisk": "LOW",
    "brandMetadataReview": false,
    "likelyBrand": "Mazoe",
    "referenceImageUrl": null,
    "notes": "Orange Crush \u2260 Raspberry. 1L \u2260 5L. Do not reuse Mazoe Blackberry."
  },
  {
    "catalogProductId": "1ac6f981-6b19-432c-befe-0fa9d36bbb3e",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Mazoe Orange Crush",
    "plannedBrand": "Mazoe",
    "plannedSizeLabel": "5L",
    "plannedCategory": "Juices",
    "brandFamily": "Mazoe",
    "acquisitionPack": "PACK_A_BEVERAGES",
    "acquisitionPriority": "BRANDED_PRIORITY_A",
    "regionalPackageRisk": "LOW",
    "brandMetadataReview": false,
    "likelyBrand": "Mazoe",
    "referenceImageUrl": null,
    "notes": "Orange Crush \u2260 Raspberry. 1L \u2260 5L. Do not reuse Mazoe Blackberry."
  },
  {
    "catalogProductId": "315a8851-86a8-4e23-b3e2-9cf85ebc2054",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Pepsi",
    "plannedBrand": "Pepsi",
    "plannedSizeLabel": "2L",
    "plannedCategory": "Soft Drinks",
    "brandFamily": "Pepsi",
    "acquisitionPack": "PACK_A_BEVERAGES",
    "acquisitionPriority": "BRANDED_PRIORITY_A",
    "regionalPackageRisk": "HIGH",
    "brandMetadataReview": false,
    "likelyBrand": "Pepsi",
    "referenceImageUrl": null,
    "notes": "500ml vs 2L separately. Not Pepsi Zero (excluded SKU)."
  },
  {
    "catalogProductId": "0bba2cd9-e9c5-487b-81dc-1b41f586f9f8",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Pepsi",
    "plannedBrand": "Pepsi",
    "plannedSizeLabel": "500ml",
    "plannedCategory": "Soft Drinks",
    "brandFamily": "Pepsi",
    "acquisitionPack": "PACK_A_BEVERAGES",
    "acquisitionPriority": "BRANDED_PRIORITY_A",
    "regionalPackageRisk": "HIGH",
    "brandMetadataReview": false,
    "likelyBrand": "Pepsi",
    "referenceImageUrl": null,
    "notes": "500ml vs 2L separately. Not Pepsi Zero (excluded SKU)."
  },
  {
    "catalogProductId": "79373171-8713-4180-b902-31d1ae3ae7a6",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Sprite",
    "plannedBrand": "Sprite",
    "plannedSizeLabel": "2L",
    "plannedCategory": "Soft Drinks",
    "brandFamily": "Sprite",
    "acquisitionPack": "PACK_A_BEVERAGES",
    "acquisitionPriority": "BRANDED_PRIORITY_A",
    "regionalPackageRisk": "HIGH",
    "brandMetadataReview": false,
    "likelyBrand": "Sprite",
    "referenceImageUrl": null,
    "notes": "500ml vs 2L separately."
  },
  {
    "catalogProductId": "c039ea2b-e38e-42f8-afa3-95fb38a62d17",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Sprite",
    "plannedBrand": "Sprite",
    "plannedSizeLabel": "500ml",
    "plannedCategory": "Soft Drinks",
    "brandFamily": "Sprite",
    "acquisitionPack": "PACK_A_BEVERAGES",
    "acquisitionPriority": "BRANDED_PRIORITY_A",
    "regionalPackageRisk": "HIGH",
    "brandMetadataReview": false,
    "likelyBrand": "Sprite",
    "referenceImageUrl": null,
    "notes": "500ml vs 2L separately."
  },
  {
    "catalogProductId": "9ad7d0b3-87f8-4b8b-b2f3-442f07c2645f",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Fizzi",
    "plannedBrand": "Fizzi",
    "plannedSizeLabel": "2L",
    "plannedCategory": "Soft Drinks",
    "brandFamily": "Fizzi",
    "acquisitionPack": "PACK_A_BEVERAGES",
    "acquisitionPriority": "BRANDED_PRIORITY_B",
    "regionalPackageRisk": "LOW",
    "brandMetadataReview": false,
    "likelyBrand": "Fizzi",
    "referenceImageUrl": null,
    "notes": "500ml vs 2L separately. Do not reuse Probottles 1L."
  },
  {
    "catalogProductId": "ca95347d-8841-4e89-897d-894f58d390dc",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Fizzi",
    "plannedBrand": "Fizzi",
    "plannedSizeLabel": "500ml",
    "plannedCategory": "Soft Drinks",
    "brandFamily": "Fizzi",
    "acquisitionPack": "PACK_A_BEVERAGES",
    "acquisitionPriority": "BRANDED_PRIORITY_B",
    "regionalPackageRisk": "LOW",
    "brandMetadataReview": false,
    "likelyBrand": "Fizzi",
    "referenceImageUrl": null,
    "notes": "500ml vs 2L separately. Do not reuse Probottles 1L."
  },
  {
    "catalogProductId": "fb489c29-16b6-4f78-a23b-e15e9c6fe557",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Mirinda Orange",
    "plannedBrand": "Mirinda",
    "plannedSizeLabel": "2L",
    "plannedCategory": "Soft Drinks",
    "brandFamily": "Mirinda",
    "acquisitionPack": "PACK_A_BEVERAGES",
    "acquisitionPriority": "BRANDED_PRIORITY_B",
    "regionalPackageRisk": "MEDIUM",
    "brandMetadataReview": false,
    "likelyBrand": "Mirinda",
    "referenceImageUrl": null,
    "notes": "Must be Orange. 500ml vs 2L separately."
  },
  {
    "catalogProductId": "8bba6346-9c14-4dd5-b443-ce20e543f92c",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Mirinda Orange",
    "plannedBrand": "Mirinda",
    "plannedSizeLabel": "500ml",
    "plannedCategory": "Soft Drinks",
    "brandFamily": "Mirinda",
    "acquisitionPack": "PACK_A_BEVERAGES",
    "acquisitionPriority": "BRANDED_PRIORITY_B",
    "regionalPackageRisk": "MEDIUM",
    "brandMetadataReview": false,
    "likelyBrand": "Mirinda",
    "referenceImageUrl": null,
    "notes": "Must be Orange. 500ml vs 2L separately."
  },
  {
    "catalogProductId": "103407c0-f3aa-4fdc-8e79-0f1cdf684c0f",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Sparletta Cream Soda",
    "plannedBrand": "Sparletta",
    "plannedSizeLabel": "2L",
    "plannedCategory": "Soft Drinks",
    "brandFamily": "Sparletta",
    "acquisitionPack": "PACK_A_BEVERAGES",
    "acquisitionPriority": "BRANDED_PRIORITY_B",
    "regionalPackageRisk": "MEDIUM",
    "brandMetadataReview": false,
    "likelyBrand": "Sparletta",
    "referenceImageUrl": null,
    "notes": "Cream Soda 2L only."
  },
  {
    "catalogProductId": "eab2767e-d7ce-4f97-a7f7-6e40368b2eb5",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Sting Energy Drink",
    "plannedBrand": "Sting",
    "plannedSizeLabel": "500ml",
    "plannedCategory": "Energy Drinks",
    "brandFamily": "Sting",
    "acquisitionPack": "PACK_A_BEVERAGES",
    "acquisitionPriority": "BRANDED_PRIORITY_B",
    "regionalPackageRisk": "HIGH",
    "brandMetadataReview": false,
    "likelyBrand": "Sting",
    "referenceImageUrl": null,
    "notes": "500ml, not the existing 250ml."
  },
  {
    "catalogProductId": "a8658bb3-a0e4-4cef-a96d-bc5adae3495d",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Schweppes Ginger Ale",
    "plannedBrand": "Schweppes",
    "plannedSizeLabel": "330ml",
    "plannedCategory": "Soft Drinks",
    "brandFamily": "Schweppes",
    "acquisitionPack": "PACK_A_BEVERAGES",
    "acquisitionPriority": "BRANDED_PRIORITY_C",
    "regionalPackageRisk": "HIGH",
    "brandMetadataReview": false,
    "likelyBrand": "Schweppes",
    "referenceImageUrl": null,
    "notes": "Ginger Ale 330ml only, not tonic or soda water."
  },
  {
    "catalogProductId": "8ad2dba7-74c6-4c60-99e8-fcd272c440b6",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Jik Bleach",
    "plannedBrand": "Jik",
    "plannedSizeLabel": "750ml",
    "plannedCategory": "Household Cleaning",
    "brandFamily": "Jik",
    "acquisitionPack": "PACK_B_HOUSEHOLD",
    "acquisitionPriority": "BRANDED_PRIORITY_A",
    "regionalPackageRisk": "LOW",
    "brandMetadataReview": false,
    "likelyBrand": "Jik",
    "referenceImageUrl": null,
    "notes": null
  },
  {
    "catalogProductId": "5b932a7c-267f-4499-9fe8-c029f0288679",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Omo Washing Powder",
    "plannedBrand": "Omo",
    "plannedSizeLabel": "2kg",
    "plannedCategory": "Laundry",
    "brandFamily": "Omo",
    "acquisitionPack": "PACK_B_HOUSEHOLD",
    "acquisitionPriority": "BRANDED_PRIORITY_A",
    "regionalPackageRisk": "MEDIUM",
    "brandMetadataReview": false,
    "likelyBrand": "Omo",
    "referenceImageUrl": null,
    "notes": null
  },
  {
    "catalogProductId": "406406a8-8cb1-4402-b494-6bd3ba48e826",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Sunlight Liquid",
    "plannedBrand": "Sunlight",
    "plannedSizeLabel": "400ml",
    "plannedCategory": "Household Cleaning",
    "brandFamily": "Sunlight",
    "acquisitionPack": "PACK_B_HOUSEHOLD",
    "acquisitionPriority": "BRANDED_PRIORITY_A",
    "regionalPackageRisk": "HIGH",
    "brandMetadataReview": false,
    "likelyBrand": "Sunlight",
    "referenceImageUrl": null,
    "notes": "Sunlight Liquid 400ml, not Trade King 750ml."
  },
  {
    "catalogProductId": "d4b236f9-f312-420c-ab00-52f1d8840ea5",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Surf Washing Powder",
    "plannedBrand": "Surf",
    "plannedSizeLabel": "1kg",
    "plannedCategory": "Laundry",
    "brandFamily": "Surf",
    "acquisitionPack": "PACK_B_HOUSEHOLD",
    "acquisitionPriority": "BRANDED_PRIORITY_A",
    "regionalPackageRisk": "MEDIUM",
    "brandMetadataReview": false,
    "likelyBrand": "Surf",
    "referenceImageUrl": null,
    "notes": "500g vs 1kg separately. Do not reuse existing 2kg."
  },
  {
    "catalogProductId": "99dea805-5a2c-4a41-8366-178530acc9c9",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Surf Washing Powder",
    "plannedBrand": "Surf",
    "plannedSizeLabel": "500g",
    "plannedCategory": "Laundry",
    "brandFamily": "Surf",
    "acquisitionPack": "PACK_B_HOUSEHOLD",
    "acquisitionPriority": "BRANDED_PRIORITY_A",
    "regionalPackageRisk": "MEDIUM",
    "brandMetadataReview": false,
    "likelyBrand": "Surf",
    "referenceImageUrl": null,
    "notes": "500g vs 1kg separately. Do not reuse existing 2kg."
  },
  {
    "catalogProductId": "35adc00a-ab71-4103-b598-c88bc8855c67",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Comfort Fabric Softener",
    "plannedBrand": "Comfort",
    "plannedSizeLabel": "2L",
    "plannedCategory": "Laundry",
    "brandFamily": "Comfort",
    "acquisitionPack": "PACK_B_HOUSEHOLD",
    "acquisitionPriority": "BRANDED_PRIORITY_B",
    "regionalPackageRisk": "MEDIUM",
    "brandMetadataReview": false,
    "likelyBrand": "Comfort",
    "referenceImageUrl": null,
    "notes": null
  },
  {
    "catalogProductId": "085e2293-90b4-454b-a4a4-0a4c897c73cc",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Handy Andy",
    "plannedBrand": "Handy Andy",
    "plannedSizeLabel": "750ml",
    "plannedCategory": "Household Cleaning",
    "brandFamily": "Handy Andy",
    "acquisitionPack": "PACK_B_HOUSEHOLD",
    "acquisitionPriority": "BRANDED_PRIORITY_B",
    "regionalPackageRisk": "MEDIUM",
    "brandMetadataReview": false,
    "likelyBrand": "Handy Andy",
    "referenceImageUrl": null,
    "notes": null
  },
  {
    "catalogProductId": "18f73c8a-06a0-4dbd-8baf-a8158b3d315d",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Vim Scouring Powder",
    "plannedBrand": "Vim",
    "plannedSizeLabel": "500g",
    "plannedCategory": "Household Cleaning",
    "brandFamily": "Vim",
    "acquisitionPack": "PACK_B_HOUSEHOLD",
    "acquisitionPriority": "BRANDED_PRIORITY_C",
    "regionalPackageRisk": "MEDIUM",
    "brandMetadataReview": false,
    "likelyBrand": "Vim",
    "referenceImageUrl": null,
    "notes": null
  },
  {
    "catalogProductId": "7bab7021-3e68-480e-8fac-96fa53f98109",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "NikNaks",
    "plannedBrand": "NikNaks",
    "plannedSizeLabel": "55g",
    "plannedCategory": "Snacks",
    "brandFamily": "NikNaks",
    "acquisitionPack": "PACK_C_SNACKS",
    "acquisitionPriority": "BRANDED_PRIORITY_A",
    "regionalPackageRisk": "MEDIUM",
    "brandMetadataReview": false,
    "likelyBrand": "NikNaks",
    "referenceImageUrl": null,
    "notes": null
  },
  {
    "catalogProductId": "572907aa-fb67-4f0f-9606-15a28343cce2",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Simba Chips",
    "plannedBrand": "Simba",
    "plannedSizeLabel": "125g",
    "plannedCategory": "Snacks",
    "brandFamily": "Simba",
    "acquisitionPack": "PACK_C_SNACKS",
    "acquisitionPriority": "BRANDED_PRIORITY_A",
    "regionalPackageRisk": "MEDIUM",
    "brandMetadataReview": false,
    "likelyBrand": "Simba",
    "referenceImageUrl": null,
    "notes": null
  },
  {
    "catalogProductId": "b6e31dd5-dc2d-47f3-b2a9-60d64fd5ba22",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Eet-Sum-Mor",
    "plannedBrand": null,
    "plannedSizeLabel": "200g",
    "plannedCategory": "Biscuits",
    "brandFamily": "Eet-Sum-Mor",
    "acquisitionPack": "PACK_C_SNACKS",
    "acquisitionPriority": "BRANDED_PRIORITY_C",
    "regionalPackageRisk": "MEDIUM",
    "brandMetadataReview": true,
    "likelyBrand": "Bakers",
    "referenceImageUrl": null,
    "notes": "Eet-Sum-Mor is a Bakers biscuit. Catalog brand is empty."
  },
  {
    "catalogProductId": "acf691e9-391d-494b-a67c-8c97b0c1b96f",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Halls",
    "plannedBrand": "Halls",
    "plannedSizeLabel": "pack",
    "plannedCategory": "Sweets",
    "brandFamily": "Halls",
    "acquisitionPack": "PACK_C_SNACKS",
    "acquisitionPriority": "BRANDED_PRIORITY_C",
    "regionalPackageRisk": "MEDIUM",
    "brandMetadataReview": false,
    "likelyBrand": "Halls",
    "referenceImageUrl": null,
    "notes": null
  },
  {
    "catalogProductId": "ae1feee1-f50d-44f1-8f0f-aaab9d5f5798",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Jelly Tots",
    "plannedBrand": null,
    "plannedSizeLabel": "100g",
    "plannedCategory": "Sweets",
    "brandFamily": "Jelly Tots",
    "acquisitionPack": "PACK_C_SNACKS",
    "acquisitionPriority": "BRANDED_PRIORITY_C",
    "regionalPackageRisk": "MEDIUM",
    "brandMetadataReview": true,
    "likelyBrand": "Nestl\u00e9",
    "referenceImageUrl": null,
    "notes": "Jelly Tots is a Nestl\u00e9 sweet. Catalog brand is empty."
  },
  {
    "catalogProductId": "42ab1134-d0cd-4767-a4b6-3f9edb7c4dc7",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Romany Creams",
    "plannedBrand": null,
    "plannedSizeLabel": "200g",
    "plannedCategory": "Biscuits",
    "brandFamily": "Romany Creams",
    "acquisitionPack": "PACK_C_SNACKS",
    "acquisitionPriority": "BRANDED_PRIORITY_C",
    "regionalPackageRisk": "MEDIUM",
    "brandMetadataReview": true,
    "likelyBrand": "Bakers",
    "referenceImageUrl": null,
    "notes": "Romany Creams is a Bakers biscuit. Catalog brand is empty."
  },
  {
    "catalogProductId": "799d9bf9-2850-457f-b09a-f4dbf2539a86",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Tennis Biscuits",
    "plannedBrand": null,
    "plannedSizeLabel": "200g",
    "plannedCategory": "Biscuits",
    "brandFamily": "Tennis Biscuits",
    "acquisitionPack": "PACK_C_SNACKS",
    "acquisitionPriority": "BRANDED_PRIORITY_C",
    "regionalPackageRisk": "MEDIUM",
    "brandMetadataReview": true,
    "likelyBrand": "Bakers",
    "referenceImageUrl": null,
    "notes": "Tennis Biscuits is a Bakers product. Catalog brand is empty."
  },
  {
    "catalogProductId": "864cee97-fc95-42ea-90bd-fad6ea347c39",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Dairibord Maheu",
    "plannedBrand": "Dairibord",
    "plannedSizeLabel": "1L",
    "plannedCategory": "Mahewu",
    "brandFamily": "Dairibord",
    "acquisitionPack": "PACK_D_BREAKFAST",
    "acquisitionPriority": "BRANDED_PRIORITY_A",
    "regionalPackageRisk": "LOW",
    "brandMetadataReview": false,
    "likelyBrand": "Dairibord",
    "referenceImageUrl": null,
    "notes": "Dairibord Maheu 1L, not Pfuko Maheu and not Cascade juice."
  },
  {
    "catalogProductId": "0186b42c-08f5-485d-8feb-bdfaae4e7931",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Aromat",
    "plannedBrand": "Aromat",
    "plannedSizeLabel": "75g",
    "plannedCategory": "Cooking Ingredients",
    "brandFamily": "Aromat",
    "acquisitionPack": "PACK_D_BREAKFAST",
    "acquisitionPriority": "BRANDED_PRIORITY_B",
    "regionalPackageRisk": "MEDIUM",
    "brandMetadataReview": false,
    "likelyBrand": "Aromat",
    "referenceImageUrl": null,
    "notes": null
  },
  {
    "catalogProductId": "837717fd-c136-4ee0-a943-16e37a8e0bb9",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Ceres Apple",
    "plannedBrand": "Ceres",
    "plannedSizeLabel": "1L",
    "plannedCategory": "Juices",
    "brandFamily": "Ceres",
    "acquisitionPack": "PACK_D_BREAKFAST",
    "acquisitionPriority": "BRANDED_PRIORITY_B",
    "regionalPackageRisk": "HIGH",
    "brandMetadataReview": false,
    "likelyBrand": "Ceres",
    "referenceImageUrl": null,
    "notes": null
  },
  {
    "catalogProductId": "00b44112-3a04-46f3-837b-c156c5d641f1",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Cerevita",
    "plannedBrand": null,
    "plannedSizeLabel": "1kg",
    "plannedCategory": "Breakfast",
    "brandFamily": "Cerevita",
    "acquisitionPack": "PACK_D_BREAKFAST",
    "acquisitionPriority": "BRANDED_PRIORITY_B",
    "regionalPackageRisk": "HIGH",
    "brandMetadataReview": true,
    "likelyBrand": "Nestl\u00e9",
    "referenceImageUrl": null,
    "notes": "Cerevita is a Nestl\u00e9 instant cereal sold in Zimbabwe/Africa. Catalog brand is empty. Brand metadata empty \u2014 photograph Nestl\u00e9 Cerevita 1kg if that is the local product."
  },
  {
    "catalogProductId": "0e4e8c41-e7d7-44ea-865a-e13b7ff5f644",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Cup-a-Soup",
    "plannedBrand": null,
    "plannedSizeLabel": "pack",
    "plannedCategory": "Convenience Foods",
    "brandFamily": "Cup-a-Soup",
    "acquisitionPack": "PACK_D_BREAKFAST",
    "acquisitionPriority": "BRANDED_PRIORITY_B",
    "regionalPackageRisk": "MEDIUM",
    "brandMetadataReview": true,
    "likelyBrand": "Knorr",
    "referenceImageUrl": null,
    "notes": "Cup-a-Soup is typically Knorr/Unilever. Confirm local SKU before photography. Brand metadata empty \u2014 photograph the exact sachet sold; flavor must match if printed."
  },
  {
    "catalogProductId": "f2a97cbe-2947-4653-b4ba-a3d2bd355099",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Ricoffy",
    "plannedBrand": "Ricoffy",
    "plannedSizeLabel": "100g",
    "plannedCategory": "Breakfast",
    "brandFamily": "Ricoffy",
    "acquisitionPack": "PACK_D_BREAKFAST",
    "acquisitionPriority": "BRANDED_PRIORITY_B",
    "regionalPackageRisk": "MEDIUM",
    "brandMetadataReview": false,
    "likelyBrand": "Ricoffy",
    "referenceImageUrl": null,
    "notes": null
  },
  {
    "catalogProductId": "cbfe5297-6e1d-4337-8d51-4c90f7f6dcf9",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Weet-Bix",
    "plannedBrand": "Weet-Bix",
    "plannedSizeLabel": "450g",
    "plannedCategory": "Breakfast",
    "brandFamily": "Weet-Bix",
    "acquisitionPack": "PACK_D_BREAKFAST",
    "acquisitionPriority": "BRANDED_PRIORITY_B",
    "regionalPackageRisk": "HIGH",
    "brandMetadataReview": false,
    "likelyBrand": "Weet-Bix",
    "referenceImageUrl": null,
    "notes": "450g Zimbabwe/Africa box, not Australian Weet-Bix."
  },
  {
    "catalogProductId": "ffac2168-9b46-4377-9150-ab72d3f3dda8",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Colgate Toothpaste",
    "plannedBrand": "Colgate",
    "plannedSizeLabel": "50ml",
    "plannedCategory": "Personal Care",
    "brandFamily": "Colgate",
    "acquisitionPack": "PACK_E_PERSONAL_CARE",
    "acquisitionPriority": "BRANDED_PRIORITY_A",
    "regionalPackageRisk": "MEDIUM",
    "brandMetadataReview": false,
    "likelyBrand": "Colgate",
    "referenceImageUrl": null,
    "notes": "50ml tube, not existing 100ml."
  },
  {
    "catalogProductId": "7abc683d-5604-40fd-83da-bd2d5b8def5b",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Geisha Soap",
    "plannedBrand": "Geisha",
    "plannedSizeLabel": "90g",
    "plannedCategory": "Personal Care",
    "brandFamily": "Geisha",
    "acquisitionPack": "PACK_E_PERSONAL_CARE",
    "acquisitionPriority": "BRANDED_PRIORITY_B",
    "regionalPackageRisk": "MEDIUM",
    "brandMetadataReview": false,
    "likelyBrand": "Geisha",
    "referenceImageUrl": null,
    "notes": null
  },
  {
    "catalogProductId": "87419e05-0ec2-48c1-aa2a-d35100951398",
    "queueKind": "BRANDED",
    "exceptionQueue": null,
    "plannedName": "Vaseline Petroleum Jelly",
    "plannedBrand": "Vaseline",
    "plannedSizeLabel": "250ml",
    "plannedCategory": "Personal Care",
    "brandFamily": "Vaseline",
    "acquisitionPack": "PACK_E_PERSONAL_CARE",
    "acquisitionPriority": "BRANDED_PRIORITY_B",
    "regionalPackageRisk": "HIGH",
    "brandMetadataReview": false,
    "likelyBrand": "Vaseline",
    "referenceImageUrl": "https://api.duts.tech/v1/media/product-image/acf20304-0077-467e-8abf-84445a6b44c0.jpg",
    "notes": "250ml petroleum jelly; Blueseal 450ml is REVIEW only."
  }
] as const;
