-- DUTS Delivery Phase 1: fulfillment, transport, pickup/dropoff, package, PINs, pricing knobs

CREATE TYPE "FulfillmentType" AS ENUM ('LOCAL_HELP', 'DELIVERY');
CREATE TYPE "OrderSource" AS ENUM ('APP', 'WEB', 'WHATSAPP');
CREATE TYPE "TransportMode" AS ENUM ('WALKING', 'BICYCLE', 'PUBLIC_TRANSPORT', 'MOTORBIKE', 'CAR');
CREATE TYPE "PackageCategory" AS ENUM ('DOCUMENTS', 'FOOD', 'GROCERIES', 'CLOTHING', 'SMALL_PARCEL', 'OTHER');

ALTER TYPE "GigStatus" ADD VALUE IF NOT EXISTS 'PACKAGE_COLLECTED';
ALTER TYPE "GigStatus" ADD VALUE IF NOT EXISTS 'EN_ROUTE_TO_DROPOFF';
ALTER TYPE "GigStatus" ADD VALUE IF NOT EXISTS 'ARRIVED_AT_DROPOFF';

ALTER TABLE "WorkerProfile" ADD COLUMN IF NOT EXISTS "transportMode" "TransportMode";

ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "fulfillmentType" "FulfillmentType" NOT NULL DEFAULT 'LOCAL_HELP';
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "orderSource" "OrderSource" NOT NULL DEFAULT 'APP';
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "pickupContactName" TEXT;
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "pickupContactPhone" TEXT;
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "pickupInstructions" TEXT;
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "dropoffAddressLine1" TEXT;
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "dropoffAddressLine2" TEXT;
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "dropoffCity" TEXT;
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "dropoffRegion" TEXT;
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "dropoffPostalCode" TEXT;
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "dropoffCountry" TEXT;
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "dropoffFormattedAddress" TEXT;
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "dropoffLatitude" DECIMAL(9,6);
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "dropoffLongitude" DECIMAL(9,6);
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "dropoffContactName" TEXT;
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "dropoffContactPhone" TEXT;
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "dropoffInstructions" TEXT;
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "packageCategory" "PackageCategory";
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "packageDescription" TEXT;
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "packageSize" TEXT;
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "packagePhotoUrl" TEXT;
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "packageNotes" TEXT;
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "estimatedDistanceKm" DECIMAL(8,3);
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "pickupPin" TEXT;
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "deliveryPin" TEXT;
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "pickupVerifiedAt" TIMESTAMP(3);
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "deliveryVerifiedAt" TIMESTAMP(3);
ALTER TABLE "Gig" ADD COLUMN IF NOT EXISTS "prohibitedItemsAck" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "PlatformSetting" ADD COLUMN IF NOT EXISTS "deliveryMaxDistanceKm" DECIMAL(6,2) NOT NULL DEFAULT 10;
ALTER TABLE "PlatformSetting" ADD COLUMN IF NOT EXISTS "deliveryBaseFeeCents" INTEGER NOT NULL DEFAULT 200;
ALTER TABLE "PlatformSetting" ADD COLUMN IF NOT EXISTS "deliveryPricePerKmCents" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "PlatformSetting" ADD COLUMN IF NOT EXISTS "deliveryMinimumFeeCents" INTEGER NOT NULL DEFAULT 200;
